/**
 * =====================================================
 * Hong Museum - Navbar Loader Component
 * 弘美术馆 - 导航栏加载组件
 * =====================================================
 * 
 * This TypeScript module dynamically loads and injects
 * the navbar component into HTML pages.
 * 
 * Usage:
 * 1. Add <div id="navbar-container"></div> where you want the navbar
 * 2. Include the compiled JS: <script src="js/navbar-loader.js" type="module"></script>
 * 3. Initialize: NavbarLoader.init({ lang: 'en', currentPage: 'home' });
 */

// Types for navbar configuration
interface NavbarConfig {
  lang: 'en' | 'cn';
  currentPage?: string;
  languageSwitchUrl?: string;
}

interface Exhibition {
  href: string;
  label: string;
  isOngoing?: boolean;
}

interface ResidencyProgram {
  href: string;
  label: string;
}

interface NavbarData {
  homeUrl: string;
  guideUrl: string;
  guideLabel: string;
  aboutUrl: string;
  aboutLabel: string;
  exhibitionsLabel: string;
  exhibitions: Exhibition[];
  residencyLabel: string;
  residencyPrograms: ResidencyProgram[];
  languageSwitchUrl: string;
  langActiveText: string;
  langInactiveText: string;
  logoAlt: string;
  ariaLabel: string;
}

// Navbar data for English version
const navbarDataEN: NavbarData = {
  homeUrl: 'home-en.html',
  guideUrl: 'guide-en.html',
  guideLabel: 'Guide',
  aboutUrl: 'about-en.html',
  aboutLabel: 'About',
  exhibitionsLabel: 'Exhibitions',
  exhibitions: [
    { href: 'digestive-ethics-en.html', label: 'Digestive Ethics', isOngoing: true },
    { href: 'mama-en.html', label: 'MAMA' },
    { href: 'the-currents-we-carry-en.html', label: 'The Currents We Carry' },
    { href: 'eleven-kinds-of-beds-en.html', label: 'Eleven Kinds of Beds' },
    { href: 'the-forebears-are-born-en.html', label: 'The Forebears are Born' },
  ],
  residencyLabel: 'Residency Program',
  residencyPrograms: [
    { href: 'situated-resonance-en.html', label: 'Situated Resonance' },
    { href: 'the-plan-of-going-home-residency-program.html', label: 'Zou Gui Project' },
  ],
  languageSwitchUrl: 'index.html',
  langActiveText: 'En',
  langInactiveText: '中文',
  logoAlt: 'Hong Museum',
  ariaLabel: '切换到中文',
};

// Navbar data for Chinese version
const navbarDataCN: NavbarData = {
  homeUrl: 'index.html',
  guideUrl: 'guide.html',
  guideLabel: '抵达',
  aboutUrl: 'about.html',
  aboutLabel: '关于',
  exhibitionsLabel: '展览',
  exhibitions: [
    { href: 'digestive-ethics-cn.html', label: '偏食', isOngoing: true },
    { href: 'mama-cn.html', label: '妈妈' },
    { href: 'the-currents-we-carry-cn.html', label: '送流水' },
    { href: 'eleven-kinds-of-beds-cn.html', label: '十一种床' },
    { href: 'the-forebears-are-born-cn.html', label: '训练祖宗' },
  ],
  residencyLabel: '驻地项目',
  residencyPrograms: [
    { href: 'situated-resonance-cn.html', label: '在地回响' },
    { href: 'zou-gui-ji-hua.html', label: '走归计划' },
  ],
  languageSwitchUrl: 'home-en.html',
  langActiveText: '中文',
  langInactiveText: 'En',
  logoAlt: '弘美术馆',
  ariaLabel: 'Switch to English',
};

/**
 * NavbarLoader class - handles loading and rendering the navbar
 */
class NavbarLoader {
  private config: NavbarConfig;
  private data: NavbarData;

  constructor(config: NavbarConfig) {
    this.config = config;
    this.data = config.lang === 'en' ? navbarDataEN : navbarDataCN;
    
    // Override language switch URL if provided
    if (config.languageSwitchUrl) {
      this.data.languageSwitchUrl = config.languageSwitchUrl;
    }
  }

  /**
   * Generate exhibition dropdown items HTML
   */
  private generateExhibitionItems(): string {
    return this.data.exhibitions
      .map(ex => {
        const label = ex.isOngoing 
          ? `${ex.label} ${this.config.lang === 'en' ? '(Ongoing)' : '(展览中)'}` 
          : ex.label;
        return `<a href="${ex.href}" class="nav-dropdown-link w-dropdown-link">${label}</a>`;
      })
      .join('\n                  ');
  }

  /**
   * Generate residency program dropdown items HTML
   */
  private generateResidencyItems(): string {
    return this.data.residencyPrograms
      .map(rp => `<a href="${rp.href}" class="nav-dropdown-link w-dropdown-link">${rp.label}</a>`)
      .join('\n                  ');
  }

  /**
   * Generate the complete navbar HTML
   */
  public generateHTML(): string {
    const langActive = this.config.lang === 'en' ? 'En' : '中文';
    const langInactive = this.config.lang === 'en' ? '中文' : 'En';
    const listTag = this.config.lang === 'en' ? 'ul' : 'ol';

    return `
<!-- Navbar Start - Generated by NavbarLoader -->
<div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar-logo-center-container shadow-three w-nav">
  <div class="container-13">
    <!-- Logo -->
    <a href="${this.data.homeUrl}" class="navbar-brand-three w-nav-brand">
      <img src="images/common/NEW-hong-museum-logo.png" loading="lazy" 
           sizes="(max-width: 479px) 98vw, (max-width: 767px) 99vw, (max-width: 2180px) 100vw, 2180px" 
           srcset="images/NEW-hong-museum-logo-p-500.png 500w, images/NEW-hong-museum-logo-p-800.png 800w, images/NEW-hong-museum-logo-p-1080.png 1080w, images/common/NEW-hong-museum-logo.png 2180w" 
           alt="${this.data.logoAlt}" class="image-6">
    </a>
    
    <div class="navbar-wrapper-three">
      <nav role="navigation" class="nav-menu-wrapper-three w-nav-menu">
        <div class="nav-menu-three">
          <${listTag} role="list" class="nav-menu-block w-list-unstyled">
            
            <!-- Guide -->
            <li class="list-item">
              <a href="${this.data.guideUrl}" class="nav-link">${this.data.guideLabel}</a>
            </li>
            
            <!-- About -->
            <li class="list-item-2">
              <a href="${this.data.aboutUrl}" class="nav-link">${this.data.aboutLabel}</a>
            </li>
            
            <!-- Exhibitions Dropdown -->
            <li class="exhibition">
              <div data-hover="false" data-delay="0" class="nav-dropdown w-dropdown">
                <div class="nav-dropdown-toggle w-dropdown-toggle">
                  <div class="nav-dropdown-icon w-icon-dropdown-toggle"></div>
                  <div class="text-block-2">${this.data.exhibitionsLabel}</div>
                </div>
                <nav class="nav-dropdown-list--ex shadow-three mobile-shadow-hide w-dropdown-list">
                  ${this.generateExhibitionItems()}
                </nav>
              </div>
            </li>
            
            <!-- Residency Program Dropdown -->
            <li class="rp">
              <div data-hover="false" data-delay="0" class="nav-dropdown---rp w-dropdown">
                <div class="nav-dropdown-toggle w-dropdown-toggle">
                  <div class="nav-dropdown-icon w-icon-dropdown-toggle"></div>
                  <div class="text-block-2">${this.data.residencyLabel}</div>
                </div>
                <nav class="nav-dropdown-list---rp shadow-three mobile-shadow-hide w-dropdown-list">
                  ${this.generateResidencyItems()}
                </nav>
              </div>
            </li>
            
            <!-- Language Switcher -->
            <li class="language">
              <a href="${this.data.languageSwitchUrl}" class="language-button" aria-label="${this.data.ariaLabel}">
                <span class="lang-active">${langActive}</span>
                <span class="lang-divider">/</span>
                <span class="lang-inactive">${langInactive}</span>
              </a>
            </li>
            
          </${listTag}>
        </div>
      </nav>
      
      <!-- Mobile Menu Button -->
      <div class="menu-button w-nav-button">
        <div class="icon-4 w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
</div>
<!-- Navbar End -->
`;
  }

  /**
   * Render the navbar into the specified container
   */
  public render(containerId: string = 'navbar-container'): void {
    const container = document.getElementById(containerId);
    if (container) {
      container.innerHTML = this.generateHTML();
      this.initWebflowNav();
    } else {
      // If no container, insert at the beginning of body
      document.body.insertAdjacentHTML('afterbegin', this.generateHTML());
      this.initWebflowNav();
    }
  }

  /**
   * Initialize Webflow navigation functionality after navbar is loaded
   */
  private initWebflowNav(): void {
    // Re-initialize Webflow if available
    if (typeof (window as any).Webflow !== 'undefined') {
      (window as any).Webflow.destroy();
      (window as any).Webflow.ready();
      (window as any).Webflow.require('ix2')?.init();
    }
  }

  /**
   * Static method to easily initialize the navbar
   */
  public static init(config: NavbarConfig): NavbarLoader {
    const loader = new NavbarLoader(config);
    
    // Wait for DOM to be ready
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', () => loader.render());
    } else {
      loader.render();
    }
    
    return loader;
  }
}

// Auto-detect language from page and initialize
function autoDetectAndInit(): void {
  const currentPath = window.location.pathname;
  const fileName = currentPath.split('/').pop() || '';
  
  // Detect language based on filename pattern
  let lang: 'en' | 'cn' = 'cn'; // Default to Chinese
  if (fileName.includes('-en.html') || fileName === 'home-en.html') {
    lang = 'en';
  }
  
  // Determine the corresponding language switch URL
  let languageSwitchUrl: string;
  if (lang === 'en') {
    // Switch from English to Chinese
    languageSwitchUrl = fileName.replace('-en.html', '-cn.html').replace('home-en.html', 'index.html');
    if (languageSwitchUrl === fileName) {
      languageSwitchUrl = 'index.html';
    }
  } else {
    // Switch from Chinese to English
    languageSwitchUrl = fileName.replace('-cn.html', '-en.html').replace('index.html', 'home-en.html');
    if (languageSwitchUrl === fileName) {
      languageSwitchUrl = 'home-en.html';
    }
  }
  
  NavbarLoader.init({
    lang,
    languageSwitchUrl,
    currentPage: fileName,
  });
}

// Export for module usage
export { NavbarLoader, NavbarConfig, NavbarData, autoDetectAndInit };

// Also attach to window for non-module usage
(window as any).NavbarLoader = NavbarLoader;
(window as any).autoDetectAndInitNavbar = autoDetectAndInit;
