/**
 * =====================================================
 * Hong Museum - Navbar Loader Component
 * 弘美术馆 - 导航栏加载组件
 * =====================================================
 *
 * This TypeScript module dynamically loads and injects
 * the navbar component into HTML pages.
 *
 * Usage:
 * 1. Add <div id="navbar-container"></div> where you want the navbar
 * 2. Include the compiled JS: <script src="js/navbar-loader.js" type="module"></script>
 * 3. Initialize: NavbarLoader.init({ lang: 'en', currentPage: 'home' });
 */
// Navbar data for English version
const navbarDataEN = {
    homeUrl: 'home-en.html',
    guideUrl: 'guide-en.html',
    guideLabel: 'Guide',
    aboutUrl: 'about-en.html',
    aboutLabel: 'About',
    exhibitionsLabel: 'Exhibitions',
    exhibitions: [
        { href: 'digestive-ethics-en.html', label: 'Digestive Ethics', isOngoing: true },
        { href: 'mama-en.html', label: 'MAMA' },
        { href: 'the-currents-we-carry-en.html', label: 'The Currents We Carry' },
        { href: 'eleven-kinds-of-beds-en.html', label: 'Eleven Kinds of Beds' },
        { href: 'the-forebears-are-born-en.html', label: 'The Forebears are Born' },
    ],
    residencyLabel: 'Residency Program',
    residencyPrograms: [
        { href: 'situated-resonance-en.html', label: 'Situated Resonance' },
        { href: 'the-plan-of-going-home-residency-program.html', label: 'Zou Gui Project' },
    ],
    languageSwitchUrl: 'index.html',
    langActiveText: 'En',
    langInactiveText: '中文',
    logoAlt: 'Hong Museum',
    ariaLabel: '切换到中文',
};
// Navbar data for Chinese version
const navbarDataCN = {
    homeUrl: 'index.html',
    guideUrl: 'guide.html',
    guideLabel: '抵达',
    aboutUrl: 'about.html',
    aboutLabel: '关于',
    exhibitionsLabel: '展览',
    exhibitions: [
        { href: 'digestive-ethics-cn.html', label: '偏食', isOngoing: true },
        { href: 'mama-cn.html', label: '妈妈' },
        { href: 'the-currents-we-carry-cn.html', label: '送流水' },
        { href: 'eleven-kinds-of-beds-cn.html', label: '十一种床' },
        { href: 'the-forebears-are-born-cn.html', label: '训练祖宗' },
    ],
    residencyLabel: '驻地项目',
    residencyPrograms: [
        { href: 'situated-resonance-cn.html', label: '在地回响' },
        { href: 'zou-gui-ji-hua.html', label: '走归计划' },
    ],
    languageSwitchUrl: 'home-en.html',
    langActiveText: '中文',
    langInactiveText: 'En',
    logoAlt: '弘美术馆',
    ariaLabel: 'Switch to English',
};
/**
 * NavbarLoader class - handles loading and rendering the navbar
 */
class NavbarLoader {
    constructor(config) {
        this.config = config;
        this.data = config.lang === 'en' ? navbarDataEN : navbarDataCN;
        // Override language switch URL if provided
        if (config.languageSwitchUrl) {
            this.data.languageSwitchUrl = config.languageSwitchUrl;
        }
    }
    /**
     * Generate exhibition dropdown items HTML
     */
    generateExhibitionItems() {
        return this.data.exhibitions
            .map(ex => {
            const label = ex.isOngoing
                ? `${ex.label} ${this.config.lang === 'en' ? '(Ongoing)' : '(展览中)'}`
                : ex.label;
            return `<a href="${ex.href}" class="nav-dropdown-link w-dropdown-link">${label}</a>`;
        })
            .join('\n                  ');
    }
    /**
     * Generate residency program dropdown items HTML
     */
    generateResidencyItems() {
        return this.data.residencyPrograms
            .map(rp => `<a href="${rp.href}" class="nav-dropdown-link w-dropdown-link">${rp.label}</a>`)
            .join('\n                  ');
    }
    /**
     * Generate the complete navbar HTML
     */
    generateHTML() {
        const langActive = this.config.lang === 'en' ? 'En' : '中文';
        const langInactive = this.config.lang === 'en' ? '中文' : 'En';
        const listTag = this.config.lang === 'en' ? 'ul' : 'ol';
        return `
<!-- Navbar Start - Generated by NavbarLoader -->
<div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar-logo-center-container shadow-three w-nav">
  <div class="container-13">
    <!-- Logo -->
    <a href="${this.data.homeUrl}" class="navbar-brand-three w-nav-brand">
      <img src="images/common/NEW-hong-museum-logo.png" loading="lazy" 
           sizes="(max-width: 479px) 98vw, (max-width: 767px) 99vw, (max-width: 2180px) 100vw, 2180px" 
           srcset="images/NEW-hong-museum-logo-p-500.png 500w, images/NEW-hong-museum-logo-p-800.png 800w, images/NEW-hong-museum-logo-p-1080.png 1080w, images/common/NEW-hong-museum-logo.png 2180w" 
           alt="${this.data.logoAlt}" class="image-6">
    </a>
    
    <div class="navbar-wrapper-three">
      <nav role="navigation" class="nav-menu-wrapper-three w-nav-menu">
        <div class="nav-menu-three">
          <${listTag} role="list" class="nav-menu-block w-list-unstyled">
            
            <!-- Guide -->
            <li class="list-item">
              <a href="${this.data.guideUrl}" class="nav-link">${this.data.guideLabel}</a>
            </li>
            
            <!-- About -->
            <li class="list-item-2">
              <a href="${this.data.aboutUrl}" class="nav-link">${this.data.aboutLabel}</a>
            </li>
            
            <!-- Exhibitions Dropdown -->
            <li class="exhibition">
              <div data-hover="false" data-delay="0" class="nav-dropdown w-dropdown">
                <div class="nav-dropdown-toggle w-dropdown-toggle">
                  <div class="nav-dropdown-icon w-icon-dropdown-toggle"></div>
                  <div class="text-block-2">${this.data.exhibitionsLabel}</div>
                </div>
                <nav class="nav-dropdown-list--ex shadow-three mobile-shadow-hide w-dropdown-list">
                  ${this.generateExhibitionItems()}
                </nav>
              </div>
            </li>
            
            <!-- Residency Program Dropdown -->
            <li class="rp">
              <div data-hover="false" data-delay="0" class="nav-dropdown---rp w-dropdown">
                <div class="nav-dropdown-toggle w-dropdown-toggle">
                  <div class="nav-dropdown-icon w-icon-dropdown-toggle"></div>
                  <div class="text-block-2">${this.data.residencyLabel}</div>
                </div>
                <nav class="nav-dropdown-list---rp shadow-three mobile-shadow-hide w-dropdown-list">
                  ${this.generateResidencyItems()}
                </nav>
              </div>
            </li>
            
            <!-- Language Switcher -->
            <li class="language">
              <a href="${this.data.languageSwitchUrl}" class="language-button" aria-label="${this.data.ariaLabel}">
                <span class="lang-active">${langActive}</span>
                <span class="lang-divider">/</span>
                <span class="lang-inactive">${langInactive}</span>
              </a>
            </li>
            
          </${listTag}>
        </div>
      </nav>
      
      <!-- Mobile Menu Button -->
      <div class="menu-button w-nav-button">
        <div class="icon-4 w-icon-nav-menu"></div>
      </div>
    </div>
  </div>
</div>
<!-- Navbar End -->
`;
    }
    /**
     * Render the navbar into the specified container
     */
    render(containerId = 'navbar-container') {
        console.log('[NavbarLoader] Rendering navbar, container:', containerId);
        const container = document.getElementById(containerId);
        console.log('[NavbarLoader] Container found:', !!container);
        if (container) {
            container.innerHTML = this.generateHTML();
            console.log('[NavbarLoader] Navbar HTML injected');
            this.initWebflowNav();
        }
        else {
            // If no container, insert at the beginning of body
            console.log('[NavbarLoader] No container, inserting at body start');
            document.body.insertAdjacentHTML('afterbegin', this.generateHTML());
            this.initWebflowNav();
        }
    }
    /**
     * Initialize Webflow navigation functionality after navbar is loaded
     */
    initWebflowNav() {
        // Re-initialize Webflow if available
        if (typeof window.Webflow !== 'undefined') {
            window.Webflow.destroy();
            window.Webflow.ready();
            window.Webflow.require('ix2')?.init();
        }
    }
    /**
     * Static method to easily initialize the navbar
     */
    static init(config) {
        const loader = new NavbarLoader(config);
        // Wait for DOM to be ready
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', () => loader.render());
        }
        else {
            loader.render();
        }
        return loader;
    }
}
// Auto-detect language from page and initialize
function autoDetectAndInit() {
    console.log('[NavbarLoader] Initializing...');
    const currentPath = window.location.pathname;
    const fileName = currentPath.split('/').pop() || '';
    // Detect language based on filename pattern
    let lang = 'cn'; // Default to Chinese
    if (fileName.includes('-en.html') || fileName === 'home-en.html') {
        lang = 'en';
    }
    // Determine the corresponding language switch URL
    let languageSwitchUrl;
    if (lang === 'en') {
        // Switch from English to Chinese
        if (fileName === 'home-en.html') {
            languageSwitchUrl = 'index.html';
        } else {
            languageSwitchUrl = fileName.replace('-en.html', '-cn.html');
        }
    }
    else {
        // Switch from Chinese to English
        if (fileName === 'index.html' || fileName === '') {
            languageSwitchUrl = 'home-en.html';
        } else if (fileName === 'zou-gui-ji-hua.html') {
            languageSwitchUrl = 'the-plan-of-going-home-residency-program.html';
        } else if (fileName === 'guide.html') {
            languageSwitchUrl = 'guide-en.html';
        } else if (fileName === 'about.html') {
            languageSwitchUrl = 'about-en.html';
        } else if (fileName === 'join.html') {
            languageSwitchUrl = 'join-en.html';
        } else {
            languageSwitchUrl = fileName.replace('-cn.html', '-en.html');
        }
    }
    NavbarLoader.init({
        lang,
        languageSwitchUrl,
        currentPage: fileName,
    });
}
// Attach to window for non-module usage
window.NavbarLoader = NavbarLoader;
window.autoDetectAndInitNavbar = autoDetectAndInit;
